### ISSUE TITLE
Seção 01 - Cabeçalho - Imagens (logos e fundo)

### ISSUE THREAD

**Issue by sauloleal** [victorborg3s/send-ideas-to-your-politician#12]
Fundo (se achar melhor pode colorir a "div" mesmo e não colocar essa imagem.
![Secao01_bg](https://user-images.githubusercontent.com/607101/88093892-0db21280-cb69-11ea-9e28-5d141cc95c69.png)

Logo Laercio
![Secao01_Logo01](https://user-images.githubusercontent.com/607101/88182032-0db42000-cc06-11ea-93bd-c1ac18cdc789.png)

Logo democratas
![Secao01_Logo02](https://user-images.githubusercontent.com/607101/88093966-27ebf080-cb69-11ea-8808-5b1ea6421b25.png)

**Comment by victorborg3s** [comment]
Solved by https://github.com/victorborg3s/send-ideas-to-your-politician/commit/371ec610d183bf63fd50f9bebdd0eec4557b042a
