### ISSUE TITLE
Campos do Formulário Principal

### ISSUE THREAD

**Issue by sauloleal** [victorborg3s/send-ideas-to-your-politician#2]
Lista de campos do formulário. Campos com asterisco são obrigatórios. A numeração antes dos nomes dos campos é apenas referência, não vai pro form.

1. Nome
(txt)

2. Whatsapp
(DDD + Número)

3. Comunidade ou Bairro * 
(txt)

4. Grau de instrução * 
(combobox)
4.1. Ensino fundamental
4.2. Ensino médio
4.3. Ensino superior
4.4. Pós-Graduação

5. Na sua opinião, qual o principal problema do município de Senhor do Bonfim? * 
(combobox)
5.1. Asfalto/Calçamento/Pavimentação de ruas
5.2. Desemprego
5.3. Esgoto/Saneamento
5.4. Estradas rurais
5.5. Iluminação pública
5.6. Infraestrutura hidríca/Falta de água
5.7. Limpeza pública/Coleta de Lixo
5.8. Qualidade de ensino
5.9. Saneamento
5.10. Saúde/Atendimento médico
5.11. Violência/Falta de segurança

6. Na sua opinião, das seguintes áreas, qual deve ser priorizada pelo próximo prefeito? *
(combobox)
6.1. Saúde
6.2. Educação
6.3. Saneamento
6.4. Emprego e renda
6.5. Meio ambiente
6.6. Agricultura
6.7. Infraestrutura

7. No campo abaixo escolha um eixo em qual sua ideia se encaixa. *
(combobox)
7.1. Assistência Social
7.2. Capacitação e Qualificação dos Servidores Públicos Municipais
7.3. Ciência e Tecnologia
7.4. Comércio e Serviços
7.5. Comunicação
7.6. Controle Da Qualidade dos Gastos
7.7. Criança e Adolescente
7.8. Defesa Social
7.9. Descentralização Administrativa
7.10. Desenvolvimento do Campo, Agricultura Familiar
7.11. Desenvolvimento e Mobilidade urbana
7.12. Desenvolvimento Econômico
7.13. Economia Solidária
7.14. Educação Esporte e Lazer e Cultura
7.15. Equilíbrio Fiscal
7.16. Fortalecimento do Planejamento e da Gestão Pública
7.17. Igualdade de Gênero
7.18. Igualdade Racial
7.19. Inclusão Produtiva
7.20. Indústria
7.21. Infraestrutura e Logística
7.22. Infraestrutura Hídrica
7.23. Inovação e Gestão do Conhecimento
7.24. Juventude
7.25. LGBTI+
7.26. Modernização da Administração Pública
7.27. Mulheres
7.28. Mundo do Trabalho
7.29. Pessoas com Deficiência
7.30. Políticas Públicas com Participação e Controle Social
7.31. Saneamento
7.32. Saúde e Política sobre Drogas
7.33. Segurança Pública
7.34. Sustentabilidade Ambiental
7.35. Turismo
7.36. Valorização dos Servidores Públicos Municipais

8. No campo abaixo, descreva sua ideia para melhorar o futuro de Serrinha.
(textarea)

**Comment by victorborg3s** [comment]
Solved with https://github.com/victorborg3s/send-ideas-to-your-politician/commit/100d3581498901b53c5489ec3c83516e1f350505
