### ISSUE TITLE
Textos para "caixas" azul e verde reservadas no layout inicial

### ISSUE THREAD

**Issue by sauloleal** [victorborg3s/send-ideas-to-your-politician#3]
**CAIXA AZUL**

O que é o programa participativo?

O Programa de Governo Participativo é um projeto voltado a população para que juntos possamos apontar, discutir e opinar sobre as políticas públicas para a nossa cidade.

Acredito que podemos defender e construir uma nova Senhor do Bonfim com a opinião de todos. PARTICIPE!

**CAIXA VERDE**

‘Cresci aqui nesta cidade maravilhosa, terra acolhedora e de gente que luta, batalha e corre atrás buscando novas conquistas. Acredito que podemos fazer sim, um governo participativo, construindo novas ideias para nossa Senhor do Bonfim.’

Obs.: Imagem layout de referência. Caixas sem bordas, apenas os textos.
![Layout_Textos](https://user-images.githubusercontent.com/607101/87342311-68bc8780-c521-11ea-9947-f1363af320af.jpeg)

**Comment by victorborg3s** [comment]
Solved with https://github.com/victorborg3s/send-ideas-to-your-politician/commit/ea8f77cc82d85b011d5f1d3d4ca963fc7f07460f
