### ISSUE TITLE
Imagens Layout

### ISSUE THREAD

**Issue by sauloleal** [victorborg3s/send-ideas-to-your-politician#4]
Imagens em .png com fundo transparente.

**Logo topo** 
![Nome Laércio](https://user-images.githubusercontent.com/607101/87342948-78889b80-c522-11ea-903e-9356caf55238.png)

**Foto Candidato**
![Laércio (sem sombra)](https://user-images.githubusercontent.com/607101/87343029-9d7d0e80-c522-11ea-96e4-ec6e189b5b40.png)

**Comment by victorborg3s** [comment]
Solves this issue: https://github.com/victorborg3s/send-ideas-to-your-politician/commit/d99988ca39ea6420af956a6ee274301a506fb7aa
