### ISSUE TITLE
Alternativa para caixas de textos (issue #3)

### ISSUE THREAD

**Issue by sauloleal** [victorborg3s/send-ideas-to-your-politician#5]
Se ficar mais tranquilo, no lugar das caixas de textos relacionadas na issue #3 , pode colocar essas duas imagens.

![Parte 02](https://user-images.githubusercontent.com/607101/87344787-66f4c300-c525-11ea-8b3c-f184e01fd290.png)

![Parte 03](https://user-images.githubusercontent.com/607101/87344791-6825f000-c525-11ea-9580-a3a73061e65a.png)

**Comment by victorborg3s** [comment]
using this images in this commit: https://github.com/victorborg3s/send-ideas-to-your-politician/commit/13fcabbea9bb48fd9b3b49abec82a14a76c52eab
